wrdLength = 0
addOne = 0
strictness = 0
letters = []
repeats = []
required = {0: '', 1: '', 2: '', 3: '', 4: '', 5: '', 6: '', 7: '', 8: '', 9: '', 10: '', 11: '', 12: '', 13: ''}
required_necessary = 0
required_preffered = 0
willPrint = 1
willScore = 1
fileType = 'txt'
startLog = 1
#tf = 'dictionaries/words_alpha.txt'
#our = 'Output.csv'
