wrdLength = 5
addOne = 1
leniency = 1
##strictness = 6
letters = ['b', 'z', 'i', 'e', 'r', 'e']
##repeats = [1]
required = {0: '', 1: '', 2: '', 3: '', 4: '', 5: '', 6: '', 7: '', 8: '', 9: '', 10: '', 11: '', 12: '', 13: ''}
required_necessary = False
required_preffered = False
willPrint = True
willScore = 1
fileType = 'txt'
startLog = False
